const OK = 200;
const BAD_REQUEST = 400;
const NOT_AUTH = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  OK, BAD_REQUEST, NOT_AUTH, NOT_FOUND, FORBIDDEN, INTERNAL_SERVER_ERROR,
};
